apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend-deploy
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: employee-frontend-container
          image: sitcbs.com/cbs-microservices/emp-frontend:v3
          ports:
            - containerPort: 80
          env:
            - name: EMPLOYEE_BACKEND_URL
              valueFrom:
                secretKeyRef:
                  name: employee-secrets
                  key: EMPLOYEE_BACKEND_URL
          resources:
            requests:
              memory: "200Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
