apiVersion: v1
kind: Service
metadata:
  name: employee-frontend-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: employee-frontend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 32600
