apiVersion: v1
kind: Service
metadata:
  name: employee-backend-svc
  namespace: dev
spec:
  type: NodePort
  selector:
    app: employee-backend
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
