apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: employee-backend-hpa
  namespace: dev
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: employee-backend-deploy
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 50
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0  # No delay in scaling up
      policies:
      - type: Percent
        value: 100  # Can increase up to 100% at once
        periodSeconds: 1
    scaleDown:
      stabilizationWindowSeconds: 0  # No delay in scaling down
      policies:
      - type: Percent
        value: 100  # Reduce pods instantly when load decreases
        periodSeconds: 1