apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-backend-deploy
  namespace: dev
spec:
  selector:
    matchLabels:
      app: employee-backend
  template:
    metadata:
      labels:
        app: employee-backend
    spec:
      containers:
      - name: employee-backend-container
        image: sitcbs.com/cbs-microservices/emp-backend:v1
        imagePullPolicy: Always
        env:
          - name: MYSQL_DB_DATASOURCE
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: MYSQL_DB_DATASOURCE
          - name: MYSQL_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: MYSQL_USER
          - name: MYSQL_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: MYSQL_ROOT_PASSWORD
        resources:
          requests:
            memory: "500Mi"
            cpu: "300m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: employee-backend
          mountPath: "/opt/opt/TCS/Metadata/"
          readOnly: true
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: employee-backend
          configMap:
            name: employee-backend-metadata-propfile
